#!/usr/bin/env python3
"""Prepare the frozen and reproducibly transformed Phase 3 paper assets."""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[1]
SOURCE_COMMIT = "3b562e72c655e6e4fb38b45ec22cfb4a1f96b530"


@dataclass(frozen=True)
class FrozenInput:
    path: str
    sha256: str


FROZEN_INPUTS = {
    "financial_figure": FrozenInput(
        "paper_assets/figures/publication_figure_2_financial_comparison.pdf",
        "4df86f6a34dbe2bc6e91daf6e8385ae2aa491009482101ae58da5142b25444a5",
    ),
    "mnist_figure": FrozenInput(
        "paper_assets/figures/publication_figure_4_mnist_benchmark.pdf",
        "96eed1a4175cd1928895887da5be8dfae9c916c0719e140c63c4e3169cd77bde",
    ),
    "financial_table": FrozenInput(
        "paper_assets/tables/publication_table_2_financial_benchmark.json",
        "fe82b17b076bf7188d470b3142acda186338cccdbc42cbea44007ee7a68a70f2",
    ),
    "mnist_table": FrozenInput(
        "paper_assets/tables/publication_table_3_mnist_benchmark.json",
        "5a6a8ace43d107cf4c09b6153f0b4cb359e53f0e6f3765396cece1e621e6d202",
    ),
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def checked_source(item: FrozenInput) -> Path:
    source = REPOSITORY / item.path
    if not source.is_file():
        raise FileNotFoundError(f"required frozen asset is missing: {item.path}")
    actual = sha256(source)
    if actual != item.sha256:
        raise ValueError(
            f"frozen asset checksum mismatch for {item.path}: "
            f"expected {item.sha256}, found {actual}"
        )
    return source


def load_json(key: str) -> dict[str, Any]:
    source = checked_source(FROZEN_INPUTS[key])
    payload = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise TypeError(f"expected a JSON object in {source}")
    return cast(dict[str, Any], payload)


def latex_value(row: dict[str, Any], field: str, *, bold: bool = False) -> str:
    value = str(row[f"{field}_display"]).replace("±", r"$\pm$")
    if value == "—":
        value = r"\textemdash"
    return rf"\textbf{{{value}}}" if bold else value


def financial_table() -> str:
    payload = load_json("financial_table")
    rows = {row["model"]: row for row in payload["rows"]}
    classification = [
        ("Majority classifier", False),
        ("Regime persistence", False),
        ("Logistic regression", True),
        ("ESN", False),
        ("GARCH(1,1)", False),
        ("QRC mean", False),
    ]
    regression = [
        ("RV persistence", False, False, False),
        ("ESN", False, True, True),
        ("GARCH(1,1)", True, False, False),
        ("QRC mean", False, False, False),
    ]
    lines = [
        r"% Generated by prepare_assets.py from the frozen Stage 2C JSON.",
        r"% SOURCE: paper_assets/tables/publication_table_2_financial_benchmark.json :: rows",
        r"\begin{center}",
        r"\begin{minipage}{\linewidth}",
        r"\centering",
        r"{\small\textbf{Table 1:} Frozen 2024--2025 financial test results. "
        r"Higher is better except for "
        r"QLIKE, RMSE and MAE. QRC is mean across three reservoir seeds; the full-precision "
        r"population standard deviations are retained in the source manifest. Bold marks "
        r"the best listed point estimate per metric. GARCH has no transition score.\par}",
        r"\smallskip",
        r"\begin{minipage}[t]{0.515\textwidth}",
        r"\centering\small",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Classifier & Macro-F1 & Bal.\ acc. & Trans.\ PR-AUC \\",
        r"\midrule",
    ]
    for model, is_best in classification:
        row = rows[model]
        lines.append(
            f"{model.replace('GARCH(1,1)', r'GARCH(1,1)')} & "
            f"{latex_value(row, 'macro_f1', bold=is_best)} & "
            f"{latex_value(row, 'balanced_accuracy', bold=is_best)} & "
            f"{latex_value(row, 'transition_pr_auc', bold=is_best)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{minipage}\hfill",
            r"\begin{minipage}[t]{0.455\textwidth}",
            r"\centering\small",
            r"\begin{tabular}{@{}lrrrr@{}}",
            r"\toprule",
            r"Forecaster & QLIKE & RMSE & MAE & Corr. \\",
            r"\midrule",
        ]
    )
    for model, qlike_best, rmse_best, mae_best in regression:
        row = rows[model]
        lines.append(
            f"{model} & {latex_value(row, 'qlike', bold=qlike_best)} & "
            f"{latex_value(row, 'rmse', bold=rmse_best)} & "
            f"{latex_value(row, 'mae', bold=mae_best)} & "
            f"{latex_value(row, 'correlation', bold=model == 'QRC mean')} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{minipage}",
            r"\end{minipage}",
            r"\end{center}",
            "",
        ]
    )
    return "\n".join(lines)


def mnist_table() -> str:
    payload = load_json("mnist_table")
    rows = {
        row["model_or_condition"]: row
        for row in payload["rows"]
        if row["section"] == "Model comparison"
    }
    order = ["Flattened logistic", "Size-controlled ESN", "Exact QRC mean"]
    lines = [
        r"% Generated by prepare_assets.py from the frozen Stage 2C JSON.",
        r"% SOURCE: paper_assets/tables/publication_table_3_mnist_benchmark.json :: "
        r"rows[section=Model comparison]",
        r"\begin{center}",
        r"\begin{minipage}{\linewidth}",
        r"\centering\small",
        r"\textbf{Table 2:} Genuine-MNIST test results. QRC values are mean $\pm$ population "
        r"standard deviation across the three frozen reservoir seeds; baselines are "
        r"single deterministic fits.\par",
        r"\smallskip",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Model & Accuracy & Macro-F1 & Bal.\ acc. & Macro AUC \\",
        r"\midrule",
    ]
    for model in order:
        row = rows[model]
        bold = model == "Size-controlled ESN"
        lines.append(
            f"{model} & {latex_value(row, 'accuracy', bold=bold)} & "
            f"{latex_value(row, 'macro_f1', bold=bold)} & "
            f"{latex_value(row, 'balanced_accuracy', bold=bold)} & "
            f"{latex_value(row, 'macro_roc_auc', bold=bold)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{minipage}",
            r"\end{center}",
            "",
        ]
    )
    return "\n".join(lines)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def asset_entry(
    destination: Path,
    source: FrozenInput,
    purpose: str,
    number: str,
    experiment: str,
    *,
    directly_included: bool,
    transformed: bool,
    transformation: str | None,
) -> dict[str, Any]:
    return {
        "destination_filename": destination.relative_to(HERE).as_posix(),
        "original_repository_path": source.path,
        "original_sha256": source.sha256,
        "copied_file_sha256": sha256(destination),
        "purpose": purpose,
        "figure_or_table_number": number,
        "source_experiment": experiment,
        "directly_included": directly_included,
        "transformed": transformed,
        "transformation": transformation,
    }


def main() -> None:
    figures = HERE / "figures"
    tables = HERE / "tables"
    figures.mkdir(parents=True, exist_ok=True)
    tables.mkdir(parents=True, exist_ok=True)

    financial_figure = figures / "financial_comparison.pdf"
    mnist_figure = figures / "mnist_benchmark.pdf"
    shutil.copyfile(checked_source(FROZEN_INPUTS["financial_figure"]), financial_figure)
    shutil.copyfile(checked_source(FROZEN_INPUTS["mnist_figure"]), mnist_figure)

    financial_tex = tables / "financial_results.tex"
    mnist_tex = tables / "mnist_results.tex"
    write_text(financial_tex, financial_table())
    write_text(mnist_tex, mnist_table())

    assets = [
        asset_entry(
            financial_figure,
            FROZEN_INPUTS["financial_figure"],
            "Financial test comparison and Stage 2A uncertainty",
            "Figure 2",
            "Frozen financial benchmark and statistical validation",
            directly_included=True,
            transformed=False,
            transformation=None,
        ),
        asset_entry(
            mnist_figure,
            FROZEN_INPUTS["mnist_figure"],
            "Genuine-MNIST model comparison and controlled robustness",
            "Figure 3",
            "Frozen genuine-MNIST benchmark",
            directly_included=True,
            transformed=False,
            transformation=None,
        ),
        asset_entry(
            financial_tex,
            FROZEN_INPUTS["financial_table"],
            "Compact two-panel financial benchmark table",
            "Table 1",
            "Frozen financial benchmark",
            directly_included=True,
            transformed=True,
            transformation=(
                "Deterministic field selection and LaTeX formatting by "
                "submission/phase3/prepare_assets.py; no numeric recomputation"
            ),
        ),
        asset_entry(
            mnist_tex,
            FROZEN_INPUTS["mnist_table"],
            "Compact genuine-MNIST model-comparison table",
            "Table 2",
            "Frozen genuine-MNIST benchmark",
            directly_included=True,
            transformed=True,
            transformation=(
                "Deterministic selection of model-comparison rows and LaTeX formatting "
                "by submission/phase3/prepare_assets.py; no numeric recomputation"
            ),
        ),
    ]
    manifest = {
        "schema_version": 1,
        "source_commit": SOURCE_COMMIT,
        "generator": "submission/phase3/prepare_assets.py",
        "generation_command": "python3 submission/phase3/prepare_assets.py",
        "policy": (
            "Frozen source checksums are verified before copying or transformation. "
            "Direct figure copies must be byte-identical."
        ),
        "assets": assets,
    }
    write_text(
        HERE / "asset_manifest.json",
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    )


if __name__ == "__main__":
    main()
